name: Promote develop to test

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create/Update PR develop -> test
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: test
          head: develop
          title: "Promote: develop → test"
          body: "PR automático para validar en **test** los cambios de `develop`."
          branch: "bot/develop-to-test"
          labels: "auto-merge"
          draft: false

      - name: Auto-approve PR
        if: steps.cpr.outputs.pull-request-number != ''
        uses: hmarr/auto-approve-action@v4
        with:
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_PAT }}
      - name: Enable auto-merge (squash)
        if: steps.cpr.outputs.pull-request-number != ''
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
